### ISSUE TITLE
Parsing PSR7 requests

### ISSUE THREAD

**Issue by gausam** [mpscholten/request-parser#11]
Hi Marc,

Was trying to use request-parser with controllers that get in PSR-7 requests (specifically `Zend\Diactoros\ServerRequest`) and obviously request-parser threw up at me.

Is it possible to get request-parse to play with PSR-7 (and not `Symfony\Component\HttpFoundation\Request`) or it'll take some plumbing to do that?

Thanks for request-parser btw!

**Comment by mpscholten** [comment]
Hey Sam, thanks for opening an issue :)

There's a [good example in the examples directory](https://github.com/mpscholten/request-parser/blob/master/examples/not-symfony.php) on how to work with `$_GET` and `$_POST`, we can use that as a starting point on how to integrate with something which is not supported out of the box.

That's how the controller helper trait looks like in the example.

``` php
trait CustomControllerHelperTrait
{
    private $queryParser;
    private $bodyParser;

    protected final function initRequestParser()
    {
        $this->queryParser = new MPScholten\RequestParser\RequestParser(
            function ($parameterName) {
                if (isset($_GET[$parameterName])) {
                    return $_GET[$parameterName];
                }
                return null;
            },
            null
        );
        $this->bodyParser = new MPScholten\RequestParser\RequestParser(
            function ($parameterName) {
                if (isset($_POST[$parameterName])) {
                    return $_POST[$parameterName];
                }
                return null;
            },
            null
        );
    }

    protected function queryParameter($name)
    {
        return $this->queryParser->get($name);
    }

    protected function bodyParameter($name)
    {
        return $this->bodyParser->get($name);
    }
}
```

Instead of using `$_GET[$parameterName]` and `$_POST[$parameterName]` we just need to use the corresponding method of the `ServerRequest` object. I just took a quick look on PRS 7 and I guess we need `getQueryParams` and  `getParsedBody`.

So we just need to change the above trait to use these methods:

``` php
trait Psr7RequestParserHelperTrait
{
    private $queryParser;
    private $bodyParser;

    protected final function initRequestParser(ServerRequest $request)
    {
        $this->queryParser = new MPScholten\RequestParser\RequestParser(
            function ($parameterName) use ($request) {
                $query = $request->getQueryParams();
                if (isset($query[$parameterName])) {
                    return $query[$parameterName];
                }
                return null;
            },
            null /* <- with this parameter you can define a custom exception to be thrown */
        );
        $this->bodyParser = new MPScholten\RequestParser\RequestParser(
            function ($parameterName) use ($request) {
                $body = $request->getParsedBody();
                if (isset($body[$parameterName])) {
                    return $body[$parameterName];
                }
                return null;
            },
            null
        );
    }

    protected function queryParameter($name)
    {
        return $this->queryParser->get($name);
    }

    protected function bodyParameter($name)
    {
        return $this->bodyParser->get($name);
    }
}
```

Then you can use the controller helper trait like this:

``` php
class MyController
{
    use Psr7RequestParserHelperTrait;

    public function __construct(ServerRequest $request)
    {
        $this->initRequestParser($request);
    }
}
```

I hope this helps for now :) If something is not working let me know.

Longterm we should add first-class PSR-7 support to the library. I'll try to tackle this later today.

**Comment by gausam** [comment]
Thanks so much Marc! I'll try your suggestions out on Sunday (on the road a.t.m)

**Comment by mpscholten** [comment]
@ihatehandles just tagged the [v1.2 release](https://github.com/mpscholten/request-parser/releases/tag/v1.2) with first-class Psr7 support 🚀  Check out [the docs](https://github.com/mpscholten/request-parser#psr7) and [the Psr7 example](https://github.com/mpscholten/request-parser/blob/master/examples/psr7.php) to see how to use it :)

Let me know in case of any issues and thanks again for opening the issue 👍

**Comment by gausam** [comment]
:fireworks: Awesome! Thanks for working on this. I'll definitely let you know how I fare.

**Comment by gausam** [comment]
Psr7 working awesomely, thanks! Future releases wishlist:
- Ability to define error messages inline (or any other way really that feels less hacky), instead of doing that in a custom exception factory where I'm forced to do a `switch ($parameter)` in order to show rightly worded error messages. Unless it's possible already?

Would also have loved: (Yes would be very easy to implement on my own and send a PR, but :clock1: will only let me do that much later)
- URL validation (basic, FILTER_VAR stuff)
- Have a between()/inRange() for numeric fields

**Comment by mpscholten** [comment]
Thanks for the feedback :) Inline error messages are a very cool idea. Url validation and numeric ranges are also very useful to have.

I've created issues for all your suggestions. I'm sure we can get them into the next release 👍

**Comment by yuvalherziger** [comment]
Yep, great insights and suggestions @ihatehandles !
I'm sure I could make some time and push a PR with one or more of them 👍
