### ISSUE TITLE
Refine the exception hierarchy

### ISSUE THREAD

**Issue by mpscholten** [mpscholten/request-parser#22]
To deliver better error messages like _"Invalid email ..."_ instead of _"Parameter email not found"_ we should improve the exception hierarchy.

Currently there's only `NotFoundException` which is basically the root exception of the library. We should add a second `InvalidValueException` for validation failures.

Then we also need to think about how we can build this into the library without breaking b.c. We also need to see how this works together with custom exceptions.

**Comment by yuvalherziger** [comment]
Agree, first of all it makes complete sense to have some sort of exception hierarchy.
One thing I anticipate we'll need to see to, would be the current tests. 

But all in all it's quite straight forward:

```
* Exception
    ---> NotFoundException
    ---> InvalidValueException
        ---> Invalid<EXPECTED_TYPE>Exception
```
