### ISSUE TITLE
Refactor README (Table of contents)

### ISSUE THREAD

**Issue by mpscholten** [mpscholten/request-parser#27]
The README is growing bigger and bigger, thus we should find a way to better organize it.

One first step should be to add a table of contents :)

cc: @yuvalherziger

**Comment by yuvalherziger** [comment]
https://github.com/mpscholten/request-parser/pull/28
Static, [because of this](https://github.com/isaacs/github/issues/215) (don't read it, it's very counterproductive 😃 )

**Comment by mpscholten** [comment]
The readme looks pretty cool now :) If you have more suggestions I'm happy to hear them 👍
