### ISSUE TITLE
Boolean Parser is not returning null on a parse error

### ISSUE THREAD

**Issue by mpscholten** [mpscholten/request-parser#5]
E.g. when the request is `GET /dashboard?includeWidgets=somethingInvalid` and the input definition is `$includeWidgets = $this->queryParameter('includeWidgets')->boolean()->required();`, `$includeWidgets` will be false.

But when doing this with the `int()` parser, e.g. passing `notANumber` to the `int()` parser, the int parser will not silently accept that input. [Instead it will threat it as an invalid value (by returning null, which will be handled later e.g. by `defaultsTo`)](https://github.com/mpscholten/request-parser/blob/master/src/IntParser.php#L11).

So if the input is not `"true"` and not `"false"`, the parser should return `null`.

**Comment by yuvalherziger** [comment]
Good point 👍  I'm on it

**Comment by yuvalherziger** [comment]
https://github.com/mpscholten/request-parser/pull/6

**Comment by yuvalherziger** [comment]
PR: https://github.com/mpscholten/request-parser/pull/7

**Comment by mpscholten** [comment]
Fixed via #8
