### ISSUE TITLE
StringParser required returns null

### ISSUE THREAD

**Issue by larrydahooster** [mpscholten/request-parser#53]
https://github.com/mpscholten/request-parser/blob/master/src/StringParser.php#L38

can this be changed to string?

**Comment by mpscholten** [comment]
Yes 👍

**Comment by larrydahooster** [comment]
awesome 💯

**Comment by mpscholten** [comment]
Can you do a quick pr? :)

**Comment by larrydahooster** [comment]
done https://github.com/mpscholten/request-parser/pull/54/files

**Comment by mpscholten** [comment]
Merged 🚀

**Comment by larrydahooster** [comment]
Nice, can you also push a new release? 🥇 
Or how do we proceed from here?

**Comment by mpscholten** [comment]
Just tagged a new version https://github.com/mpscholten/request-parser/releases/tag/v1.5.1 :)

**Comment by larrydahooster** [comment]
nice, thanks for all the effort. I know the chain is kind of annoying, but it also needs an update on https://packagist.org/packages/mpscholten/request-parser

:-/

**Comment by mpscholten** [comment]
Just updated it :)
